# Generated by Django 4.1.7 on 2023-04-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("descriptions", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField(default=0)),
                ("digital", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="product/%Y/%m"),
                ),
                ("locations", models.CharField(max_length=200)),
                ("stars", models.IntegerField(default=1)),
                ("type_id", models.IntegerField(blank=True, default=1, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=100)),
                ("employee_no", models.IntegerField(default=1)),
                ("hotel_location", models.CharField(max_length=100)),
                ("stars", models.IntegerField(default=1)),
                ("bio", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="hotel.png", null=True, upload_to="hotels"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel_type",
                    models.CharField(
                        choices=[("restourant", "Restourant"), ("hotel", "Hotel")],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="products",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AlterModelOptions(
            name="ordersuccess",
            options={"ordering": ["-ordered_at"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name", "username"]},
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Recommended",
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.hoteltype",
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.food"
            ),
        ),
        migrations.AlterField(
            model_name="ordersuccess",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.food"
            ),
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
